MusicApp - Final/MusicApp/Models/Letters.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicApp.Models
{
    public class Letters
    {
        internal object Term;

        public enum SemesterType
        {
            Semester1,
            Semester2
        }
        public int Id { get; set; }
        
        //StudentFk
        [ForeignKey("Students")]
        public int StudentsId { get; set; }
        public virtual Students Students { get; set; }

        //LessonTYFk
        [ForeignKey("LessonTY")]
        [Display(Name = "Term & Year")]
        public int LessonTYId { get; set; }
        public virtual LessonTY LessonTY { get; set; }

        //LessonDTfk
        [ForeignKey("LessonDT")]
        [Display(Name = "Start & End Date")]
        public int LessonDTId { get; set; }
        public virtual LessonDT LessonDT { get; set; }

        //Semester
        [Display(Name = "Semester")]
        public SemesterType Semester { get; set; }

        //Payment Details
        //Bank Details
        [Display(Name = "Bank")]
        public string BankId { get; set; }

        [Display(Name = "Account Name")]
        public string AccName { get; set; }

        [Display(Name = "BSB Number")]
        public int BSBNo { get; set; }

        [Display(Name = "Account Number")]
        public int AccNo { get; set; }

        [Display(Name = "Cost")]
        [DataType(DataType.Currency), Required]
        public int Cost { get; set; }

        [Display(Name = "Paid")]
        public Boolean Paid { get; set; }

        [Display(Name = "Signature")]
        public string Signature { get; set; }
    }
}

MusicApp - Final/MusicApp/Controllers/LettersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicApp.Data;
using MusicApp.Models;
using System.Net.Mail;
using System.Text;

namespace MusicApp.Controllers
{
    public class LettersController : Controller
    {
        private readonly MusicAppContext _context;
        public int sID;
        public string fName;

        public LettersController(MusicAppContext context)
        {
            _context = context;
        }

        // GET: Letters
        public async Task<IActionResult> Index(string searchString)
        {
            var musicAppContext = from l in _context.Letters.Include(l => l.LessonDT).Include(l => l.LessonTY).Include(l => l.Students)
                                  select l;

            if (!string.IsNullOrEmpty(searchString))
            {
                musicAppContext = musicAppContext.Where(l => l.AccName.Contains(searchString));
            }
            return View(await musicAppContext.ToListAsync());
        }

        // GET: Letters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var letters = await _context.Letters
                .Include(l => l.LessonDT)
                .Include(l => l.LessonTY)
                .Include(l => l.Students)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (letters == null)
            {
                return NotFound();
            }

            var letter = _context.Letters.Find(id);
            fName = letter.Students.FullName;

            fName = _context.Students
                .Where(s => s.Id == 1)
                .Select(s => s.FullName)
                .FirstOrDefault();

            if (fName == null)
            {
                return NotFound();
            }

            fName = fName.Trim();
            return View(letters);
        }

        // GET: Letters/Create
        public IActionResult Create()
        {
            ViewData["LessonDTId"] = new SelectList(_context.LessonDT, "Id", "StartDate");
            ViewData["LessonTYId"] = new SelectList(_context.LessonTY, "Id", "Term");
            ViewData["StudentsId"] = new SelectList(_context.Students, "Id", "FullName");
            ViewData["Semester"] = new SelectList(Enum.GetValues(typeof(Letters.SemesterType)));
            return View();
        }

        // POST: Letters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentsId,LessonTYId,LessonDTId,Semester,BankId,AccName,BSBNo,AccNo,Cost,Paid,Signature")] Letters letters)
        {
            if (ModelState.IsValid)
            {
                _context.Add(letters);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LessonDTId"] = new SelectList(_context.LessonDT, "Id", "StartDate", letters.LessonDTId);
            ViewData["LessonTYId"] = new SelectList(_context.LessonTY, "Id", "Term", letters.LessonTYId);
            ViewData["StudentsId"] = new SelectList(_context.Students, "Id", "FullName", letters.StudentsId);
            ViewData["Semester"] = new SelectList(Enum.GetValues(typeof(Letters.SemesterType)));
            return View(letters);
        }

        // GET: Letters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var letters = await _context.Letters.FindAsync(id);
            if (letters == null)
            {
                return NotFound();
            }
            ViewData["LessonDTId"] = new SelectList(_context.LessonDT, "Id", "StartDate", letters.LessonDTId);
            ViewData["LessonTYId"] = new SelectList(_context.LessonTY, "Id", "Term", letters.LessonTYId);
            ViewData["StudentsId"] = new SelectList(_context.Students, "Id", "FullName", letters.StudentsId);
            ViewData["Semester"] = new SelectList(Enum.GetValues(typeof(Letters.SemesterType)));
            return View(letters);
        }

        // POST: Letters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StudentsId,LessonTYId,LessonDTId,Semester,BankId,AccName,BSBNo,AccNo,Cost,Paid,Signature")] Letters letters)
        {
            if (id != letters.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(letters);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LettersExists(letters.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LessonDTId"] = new SelectList(_context.LessonDT, "Id", "StartDate", letters.LessonDTId);
            ViewData["LessonTYId"] = new SelectList(_context.LessonTY, "Id", "Term", letters.LessonTYId);           
            ViewData["StudentsId"] = new SelectList(_context.Students, "Id", "FullName", letters.StudentsId);
            ViewData["Semester"] = new SelectList(Enum.GetValues(typeof(Letters.SemesterType)));
            return View(letters);
        }

        // GET: Letters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var letters = await _context.Letters
                .Include(l => l.LessonDT)
                .Include(l => l.LessonTY)
                .Include(l => l.Students)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (letters == null)
            {
                return NotFound();
            }

            return View(letters);
        }

        // POST: Letters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var letters = await _context.Letters.FindAsync(id);
            _context.Letters.Remove(letters);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LettersExists(int id)
        {
            return _context.Letters.Any(e => e.Id == id);
        }
        //POST: Letters/Send/S
        public async Task<IActionResult> Send(int? id)
        {
            {
                var invoice = await _context.Letters
                .FirstOrDefaultAsync(m => m.Id == sID);

                string Students = _context.Students
                    .Where(s => s.Id == id)
                    .Select(s => s.FullName)
                    .SingleOrDefault();

                var Term = _context.LessonTY
                    .Where(s => s.Id == id)
                    .Select(s => s.Term)
                    .SingleOrDefault();

                var Year = _context.LessonTY
                   .Where(s => s.Id == id)
                   .Select(s => s.Year)
                   .SingleOrDefault();

                var Semester = _context.Letters
                   .Where(s => s.Id == id)
                   .Select(s => s.Semester)
                   .SingleOrDefault();

                var StartDate = _context.LessonDT
                    .Where(s => s.Id == id)
                    .Select(s => s.StartDate)
                    .SingleOrDefault();

                var EndDate = _context.LessonDT
                    .Where(s => s.Id == id)
                    .Select(s => s.EndDate)
                    .SingleOrDefault();

                Decimal Cost = _context.Letters
                    .Where(s => s.Id == id)
                    .Select(s => s.Cost)
                    .SingleOrDefault();

                string Bank = _context.Letters
                    .Where(s => s.Id == id)
                    .Select(s => s.BankId)
                    .SingleOrDefault();

                string emailQuery = _context.Students
                    .Where(s => s.Id == id)
                    .Select(s => s.ContactEmail)
                    .SingleOrDefault();

                string AccName = _context.Letters
                    .Where(s => s.Id == id)
                    .Select(s => s.AccName)
                    .SingleOrDefault();

                int BSB = _context.Letters
                    .Where(s => s.Id == id)
                    .Select(s => s.BSBNo)
                    .SingleOrDefault();

                int AccNo = _context.Letters
                    .Where(s => s.Id == id)
                    .Select(s => s.AccNo)
                    .SingleOrDefault();

                string Signature = _context.Letters
                    .Where(s => s.Id == id)
                    .Select(s => s.Signature)
                    .SingleOrDefault();

                Console.WriteLine("Hello");


                //string to = emailQuery; //To address    
                //string from = "HIT339TEST@gmail.com"; //From address    
                //MailMessage message = new MailMessage(from, to);

MusicApp - Final/MusicApp/Views/Letters/Create.cshtml
@model MusicApp.Models.Letters

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Letters</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentsId" class="control-label"></label>
                <select asp-for="StudentsId" class ="form-control" asp-items="ViewBag.StudentsId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LessonTYId" class="control-label"></label>
                <select asp-for="LessonTYId" class ="form-control" asp-items="ViewBag.LessonTYId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LessonDTId" class="control-label"></label>
                <select asp-for="LessonDTId" class ="form-control" asp-items="ViewBag.LessonDTId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <select asp-for="Semester" class="form-control" asp-items="ViewBag.Semester"></select>
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankId" class="control-label"></label>
                <input asp-for="BankId" class="form-control" />
                <span asp-validation-for="BankId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccName" class="control-label"></label>
                <input asp-for="AccName" class="form-control" />
                <span asp-validation-for="AccName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BSBNo" class="control-label"></label>
                <input asp-for="BSBNo" class="form-control" />
                <span asp-validation-for="BSBNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccNo" class="control-label"></label>
                <input asp-for="AccNo" class="form-control" />
                <span asp-validation-for="AccNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Paid" /> @Html.DisplayNameFor(model => model.Paid)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Signature" class="control-label"></label>
                <input asp-for="Signature" class="form-control" />
                <span asp-validation-for="Signature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicApp - Final/MusicApp/Views/Letters/Delete.cshtml
@model MusicApp.Models.Letters

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Letters</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Students)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Students.ContactEmail)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LessonTY)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LessonTY.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LessonDT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LessonDT.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BSBNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BSBNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Signature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Signature)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MusicApp - Final/MusicApp/Views/Letters/Details.cshtml
@model MusicApp.Models.Letters

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Letters</h4>
    <hr />
    <p>
        Dear @Html.DisplayFor(model => model.Students.FullName),
    </p>
    <p>
        Welcome to all existing students and new students. @Html.DisplayFor(model => model.LessonTY.Term) will commence @Html.DisplayFor(model => model.LessonDT.StartDate).
        Please ensure your payment is finalised by @Html.DisplayFor(model => model.LessonDT.EndDate). If a student is no longer attending lessons, please email the CYCM to be removed off the email list.
    </p>
    <p>
        If paying by Bank Transfer - EFT, pleae forward a copy of your payment to the office, to follow up and allocate to the student.
    </p>
    <p>Payment Details:</p>
    <p>Ref#: REFERENCE NUMBER</p>
    <p>Student: @Html.DisplayFor(model => model.Students.FullName)</p>
    <p>Amount: @Html.DisplayFor(model => model.Cost)</p>

    <p>
        Please follow "http://webpay.cdu.edu.au/musicschool/tran-type=006&REFNO=reference_number&CUSTNAME=lastname_firstname&PARENTSNAME=parents_name&UNITAMOUNTINCTAX=amount" to make payment for @Html.DisplayFor(model => model.LessonTY.Term), @Html.DisplayFor(model => model.LessonTY.Year).
    </p>
    <p>
        Apply for your sport Vouchers for @Html.DisplayFor(model => model.Semester), @Html.DisplayFor(model => model.LessonTY.Year), please visit "http://www.sportvoucher.nt.gov.au", as schools are no longer providing students with sport vouchers.
    </p>

    <p>*Alternatively pay via Bank Transfer - EFT - CDU bank details, delete old bank details:*</p>

    <p>New Bank Details:</p>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BankId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BankId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BSBNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BSBNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
    </dl>

    <p>Reference number - please inlclude 'CYCM, Reference number and student name'</p>

    <p>The CYCM is committed to providing students with quality lessons in a positive learning environment</p>

    <dl class="row">
        <dd class="col-sm-10">
            Regards,
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Signature)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a value="Print" onClick="window.print()" asp-route-id="@Model.Id">Print</a> |
    <a asp-action="Send" asp-route-id="@Model.Id">Send</a>  |
    <a asp-action="Index">Back to List</a>
</div>

MusicApp - Final/MusicApp/Views/Letters/Edit.cshtml
@model MusicApp.Models.Letters

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Letters</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="StudentsId" class="control-label"></label>
                <select asp-for="StudentsId" class="form-control" asp-items="ViewBag.StudentsId"></select>
                <span asp-validation-for="StudentsId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LessonTYId" class="control-label"></label>
                <select asp-for="LessonTYId" class="form-control" asp-items="ViewBag.LessonTYId"></select>
                <span asp-validation-for="LessonTYId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LessonDTId" class="control-label"></label>
                <select asp-for="LessonDTId" class="form-control" asp-items="ViewBag.LessonDTId"></select>
                <span asp-validation-for="LessonDTId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <select asp-for="Semester" class="form-control" asp-items="ViewBag.Semester"></select>
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankId" class="control-label"></label>
                <input asp-for="BankId" class="form-control" />
                <span asp-validation-for="BankId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccName" class="control-label"></label>
                <input asp-for="AccName" class="form-control" />
                <span asp-validation-for="AccName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BSBNo" class="control-label"></label>
                <input asp-for="BSBNo" class="form-control" />
                <span asp-validation-for="BSBNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccNo" class="control-label"></label>
                <input asp-for="AccNo" class="form-control" />
                <span asp-validation-for="AccNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Paid" /> @Html.DisplayNameFor(model => model.Paid)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Signature" class="control-label"></label>
                <input asp-for="Signature" class="form-control" />
                <span asp-validation-for="Signature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicApp - Final/MusicApp/Views/Letters/Index.cshtml
@model IEnumerable<MusicApp.Models.Letters>

@{
    ViewData["Title"] = "Letter";
}

<h1>Letter</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Letters" asp-action="Index" method="get">
    <p>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Students)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BankId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BSBNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Paid)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Students.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BankId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BSBNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paid)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Invoice</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |

                </td>
            </tr>
        }
    </tbody>
</table>